version: '2.1'

services:
  mysql:
    container_name: mysql
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_ROOT_HOST
    ports:
      - '${DB_PORT}'
    volumes:
      - ./etc/docker/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - ./docker/mysql:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 30s
      timeout: 10s
      retries: 5
# tag::keycloak-theme-docker-setup[]
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:10.0.1
    depends_on:
      - mysql
    ports:
      - '8888:8080'
    links:
      - mysql
      - maildev
    volumes:
      - ./dist/holisticon/:/opt/jboss/keycloak/themes/holisticon/
# end::keycloak-theme-docker-setup[]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      KEYCLOAK_PASSWORD: 'admin'
      KEYCLOAK_USER: 'admin'
      KEYCLOAK_LOGLEVEL: 'INFO'
      ROOT_LOGLEVEL: 'INFO'

  maildev:
    container_name: maildev
    image: djfarrelly/maildev:1.0.0-rc2
    ports:
      - '9999:80'
      - '25'
